name = "daily-dles-hono"
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "games"
database_id = "5b939166-a476-4e6e-b2f7-fa772cb5e9b0"
preview_database_id = "DB"

# [ai]
# binding = "AI"
